### PR TITLE
Sp 55 edit projects

### PR DESCRIPTION
**Pull request by hootxdontxboot**
Screenshot 2024-10-24 at 2 56 56 PM
when no date entered it defaults to null but fills in 1969 date for whatever reason

### CODE REVIEW

**Review by asan6602 — DISMISSED** [review]

**Comment by GiessC** [comment]
Everything looks good. To add onto the `endDate` validation issues, you can set an `endDate` in the future. I would say just like the other validation issue, address that in a separate ticket for the sake of moving this forward

**Review by GiessC — DISMISSED** [review]

**Review by GiessC — DISMISSED** [review]
Creating and deleting a project works as intended.

Editing a project does not make an API call so the changes aren't saved.
You'll need to resolve those merge conflicts before merging into master.

There are some styling issues currently:
- The edit and delete buttons are at the bottom of the project cards instead of aligned on the right
- All sections below `Projects` are now engulfed by the `Projects` section.

image

**Comment by asan6602** [comment]
**Problems in running frontend**

Duplicate identifier 'Job'.
- src/app/portfolio/portfolio.component.ts:5:10 
- src/app/portfolio/portfolio.component.ts:11:10 

 
Duplicate identifier 'MilestoneService'.
- src/app/portfolio/portfolio.component.ts:7:10 
- src/app/portfolio/portfolio.component.ts:13:9 


 Duplicate identifier 'ScreenSizeService'.
- src/app/portfolio/portfolio.component.ts:14:9 
- src/app/portfolio/portfolio.component.ts:21:10


Looks you forgot to get rid of a few imports

**Comment by asan6602** [comment]
image
should probably make the buttons consistent

**Review by asan6602 — DISMISSED** [review]

**Review by gregSWEN — DISMISSED** [review]
Approved by group during Tuesday Meeting

**Review by himeluddin — APPROVED** [review]

**Review by gregSWEN — APPROVED** [review]
re - approving it

**Pull request merged**
